version: '3'

services:
  db1:
    image: postgres
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: tasks
    ports:
      - "${DB_1}:5432"
    volumes:
      - db1-data:/var/lib/postgresql/data
      - ./db/tasks.sql:/docker-entrypoint-initdb.d/tasks.sql

  db2:
    image: postgres
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: tasks
    ports:
      - "${DB_2}:5432"
    volumes:
      - db2-data:/var/lib/postgresql/data
      - ./db/tasks.sql:/docker-entrypoint-initdb.d/tasks.sql

  backend:
    build: 
      context: ./backend
    ports:
      - "${BACKEND_PORT}":${BACKEND_PORT}
    depends_on:
      - db1
      - db2
    environment:
      - DATABASE_URL1=postgresql://user1:password1@db1:5432/todo1
      - DATABASE_URL2=postgresql://user2:password2@db2:5432/todo2


volumes:
  db1-data:
  db2-data: